### ISSUE TITLE
InfluxDB Losing Database and Users After Service Restart

### ISSUE THREAD

**Issue by falnemer** [hassio-addons/addon-influxdb#6] opened 2018-09-20 19:40 UTC
# Problem/Motivation
When I restart my InfluxDB addon service, it would remove the users and databases it created.

## Expected behavior
I expect my database and users to remain.

## Actual behavior
The databses and users are removed

## Steps to reproduce
When I log into Hass.IO and go to the addons, I launch the InfluxDB addon and click the restart service.

I did hear back from a reddit thread that another user was having this issue. It was due to the config section having `"auth": true`

[Here is the link to the reddit thread/comment](https://www.reddit.com/r/homeassistant/comments/9hayuh/losing_influxdb_when_restarting_hassio_service/e6b8o90)

Here is my configuration and it now works by changing auth to false:

{
  "log_level": "info",
  "username": "##remark##",
  "password": "##remark##",
  "auth": false,
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "ipv6": true
}

## Proposed changes
Update InfluxDB to allow for authentication.

**Comment by tjorim** [comment] 2018-09-20 21:31
Hm, just noticed my influxdb is empty as well. Missing the database and all users gone, don't remember restarting it tho. Can confirm I do have auth enabled (default) as well.

**Comment by frenck** [comment] 2018-09-23 19:46
I'm running the add-on with `auth: true` myself and cannot reproduce this error. I've tried on multiple test systems and still retains across restarts

**Comment by petrfaitl** [comment] 2018-09-24 04:14
Same issue here. I've tried switching all the flags on/off (auth, ssl, ip6) to no avail.

System Log reports
`18-09-24 04:03:07 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_influxdb
18-09-24 04:03:12 WARNING (MainThread) [hassio.api.security] /addons/a0d7b954_influxdb/info no role for a0d7b954_influxdb`

And log from InfluxDB add-on

`2018/09/24 16:08:34 Using configuration at: /etc/kapacitor/kapacitor.conf
ts=2018-09-24T16:08:35.509+12:00 lvl=error msg="encountered error" service=run err="open server: open service *influxdb.Service: failed to link subscription on startup: authorization failed"
run: open server: open service *influxdb.Service: failed to link subscription on startup: authorization failed
INFO: Starting the Kapacitor`

**Comment by frenck** [comment] 2018-09-24 15:12
@petrfaitl 
The first error is expected since that is related to a new feature of Hassio. This is currently a warning and has no effect on the add-on. The implementation of this new feature will be done soon.

The second error is perfectly normal/fine. Kapacitor starts quicker then InfluxDB, so it fails to connect the first time. It will eventually pick up as soon as InfluxDB is started.

So both of those errors are not related, known and kinda expected.

**Comment by frenck** [comment] 2018-09-24 22:39
OK, somebody actually handed over some big logs that showed the issue.

And the thing is: InfluxDB uses the Hassio Add-on API token as an internal password.
Recently Hassio implemented a new feature: rotation of API token on startup of the add-on (before it was fixed per add-on instance for the lifetime of the add-on).

This causes issues now.

**Good news**: Your data isn't gone. It is just Chronograf & Kapacitor who can't access the data.
If you have external users configured (Home Assistant or Grafana), they should be able to connect (based on first initial review of the situation).

I'm tagging this issue high priority and will provide updates ASAP.

**Comment by pyrosmiley** [comment] 2018-09-25 05:54
Thanks so much for jumping on this @frenck -- really appreciate the work you put in for these add-ons.

**Comment by frenck** [comment] 2018-09-25 11:01
I've added in a fix for this issue on the development branch, this fix needs testing.
But since I'm now able to reproduce this, that will be done ASAP.

I currently do not have access to a slow device (Raspberry Pi), which is a cause of this problem as well.
I'll report back in a couple of hours.

**Comment by frenck** [comment] 2018-09-25 19:53
OK, so reproducing fails on my test setups (I guess the size of the database matters in this case...).

This release improves on many levels, so I'll do some final testing on the new Hassio API security stuff and will release it tonight.

In this case, I'm going to **assume** this fixes it. (It sure won't break it...)

I'll leave this issue open and hope someone is willing to report back on it after upgrading.

**Comment by frenck** [comment] 2018-09-25 20:16
# 🎉 Released v1.1.0

Please give me some feedback on this 🙏

**Comment by smbunn** [comment] 2018-09-25 20:28
Hi Frenck, checked this morning (my time in New Zealand) and V1.1.0 is not coming up in Hass.io on my Raspberry PI.  I still have 1.0.1 installed and no 'update' option.  Can I force an update?  Can I uninstall and reinstall without losing my data?

**Comment by matthew73210** [comment] 2018-09-25 20:46
Hey,

Found a quick fix for my machine, remove this from configuration.yaml

http:
  api_password: xxx

Workes now for me.

**Comment by matthew73210** [comment] 2018-09-25 20:46
I've got the update too, but it still failed untill i removed http...

**Comment by frenck** [comment] 2018-09-25 20:46
@matthew73210 That cannot possibly be related at all!
The add-on does not communicate with Home Assistant.... so disable or enable the password would not do anything..

**Comment by frenck** [comment] 2018-09-25 20:47
@smbunn In the Hass.io add-on store there is a reload button in the top right. Hit it!

**Comment by smbunn** [comment] 2018-09-25 20:49
OK, that allowed me to see the update which I am installing now.

**Comment by matthew73210** [comment] 2018-09-25 20:53
@frenck Okay maybe a glitch for 'my' system, because that's the only thing I changed and it started working. Thanks for the rapid update.

**Comment by smbunn** [comment] 2018-09-25 20:54
I have completed the update and InfluxDB will not start:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: InfluxDB v1.1.0
 Scalable datastore for metrics, events, and real-time analytics
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 armhf / HassOS 1.11 / HA 0.78.3 / SU 131 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
INFO: Password is NOT in the Have I Been Pwned database! Nice!
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 11-nginx.sh: executing... 
Adding password for user admin
[cont-init.d] 11-nginx.sh: exited 0.
[cont-init.d] 20-system-users.sh: executing... 
/var/run/s6/etc/cont-init.d/20-system-users.sh: line 17: hassio.log.info: command not found
[cont-init.d] 20-system-users.sh: exited 127.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.
 
 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.

**Comment by matthew73210** [comment] 2018-09-25 20:55
Did you restart hassio?

**Comment by frenck** [comment] 2018-09-25 20:55
@smbunn Thanks! That is my bad!
The good news: You are hitting the part I expected to be the issue.

Going to create a hotfix right now!

**Comment by smbunn** [comment] 2018-09-25 20:56
About to do that now

**Comment by frenck** [comment] 2018-09-25 20:59
🚑 Created patch, building an edge release right now. As soon as that one finished, I'll tag a v1.1.1 release.

**Comment by smbunn** [comment] 2018-09-25 21:27
It is running!  My databases are back.  My users are back!

Thanks Frenck, you are a star!

**Comment by frenck** [comment] 2018-09-25 21:28
Thank you so much for helping me out on this @smbunn! ❤️ 

I've created issue #7 to make some more improvement and tuning down the warnings in the logs.

**Comment by frenck** [comment] 2018-09-25 21:35
I call this resolved for now. If someone still has issues with this, please re-open this issue or just add a comment to it. (This issue will remain unlocked for 30 days).

**Comment by frenck** [comment] 2018-09-26 08:18
Hmmm... seems like 60 seconds is not enough wait time for your system @rpeders...
Reopening ticket to tackle this.

**Comment by Pteranodon** [comment] 2018-09-29 01:34
My influxdb also won't start but I'm always only getting INFO: InfluxDB init process in progress... 5 times before [cont-init.d] 20-system-users.sh: exited 1.

Full log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: InfluxDB v1.1.1
 Scalable datastore for metrics, events, and real-time analytics
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 armhf / HassOS 1.11 / HA 0.79.0 / SU 131 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
INFO: Password is NOT in the Have I Been Pwned database! Nice!
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 11-nginx.sh: executing... 
Adding password for user ha_admin
[cont-init.d] 11-nginx.sh: exited 0.
[cont-init.d] 20-system-users.sh: executing... 
INFO: InfluxDB init process in progress...
INFO: InfluxDB init process in progress...
INFO: InfluxDB init process in progress...
INFO: InfluxDB init process in progress...
INFO: InfluxDB init process in progress...
[cont-init.d] 20-system-users.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.
 
 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
/var/run/s6/etc/cont-init.d/20-system-users.sh: line 9:   625 Killed                  influxd
```

**Comment by frenck** [comment] 2018-09-29 08:10
@Pteranodon That is not related. This issue is about losing users & databases, you are now reporting in an issue about a fatal error of the add-on, causing it not to start.

Don't go off-topic on GitHub issues, that is really not appreciated.  I've created issues #9 for you.

**Comment by Pteranodon** [comment] 2018-09-30 03:01
Obviously I thought the issue was related or I wouldn't have commented
where I did.

This issue (#9) is possibly/likely due to a corrupt influxdb caused by the
raspberry pi restarting itself unexpectedly.

**Comment by frenck** [comment] 2018-11-08 21:04
For the upcoming release, I've improved this waiting for InfluxDB logic overall, which takes care of the remaining issues listed here.

Closing this issue.

**Closed by frenck** 2018-11-08 21:04 UTC
Labels: Priority: Critical, Status: In progress, Type: Bug

**Comment by FinMati** [comment] 2018-11-08 21:32
I have also that "INFO: InfluxDB init process in progress..." until failure. When that new release should be out?

**Comment by frenck** [comment] 2018-11-08 21:32
I've just finished the cross-platform tests, so I'm currently writing the release notes.
