### ISSUE TITLE
Publish port 8089 UDP to enable ProxMox to write to the db

### ISSUE THREAD

**Issue by olivierfaber** [hassio-addons/addon-influxdb#180] opened 2021-06-23 08:33 UTC
# Problem/Motivation

Proxmox only works with InfluxDB on UDP (8089). Right now, only TCP is published from the container.
HTTP could also be an option, but it has a certificate that's only valid when accessed on DNS and I don't feel comfortable opening these ports to the outside world.

## Expected behavior

Have Proxmox write it's metrix to the influxdb addon through UDP port 8089

![Screenshot_8](https://user-images.githubusercontent.com/25980325/123064260-67bcf700-d40e-11eb-8e19-3f89b6e4455c.png)

## Proposed changes

Add a configuration option to open UDP 8089 (closed by default).

**Comment by frenck** [comment] 2021-06-23 08:36
Duplicate of many others.

**Closed by frenck** 2021-06-23 08:36 UTC
