### ISSUE TITLE
Update to 4.0.0 deleted user and database(s)

### ISSUE THREAD

**Issue by bcutter** [hassio-addons/addon-influxdb#109] opened 2021-01-23 00:34 UTC
# Problem/Motivation

> All databases and users are deleted

## Expected behavior

> Update to v4.0.0. Everything works like before, users, databases and data are available.

## Actual behavior

> Update to v4.0.0. Databases are deleted and users are empty too. Dashboards have no data.

## Steps to reproduce

> Update to v4.0.0.

## Proposed changes

> Check what´s wrong with the update, urgently!

All my homeassistant data is gone. Of course I have a backup, unfortunately that one´s almost 24 hours old so 1 day of data lost.

Did not restore it yet, still hope it´s just a small bug and data is still there... did already restart the addon, did not change anything unfortunately :-(

![grafik](https://user-images.githubusercontent.com/13799156/105562640-4c44a780-5d1b-11eb-845f-5f1cb8500787.png)

![grafik](https://user-images.githubusercontent.com/13799156/105562650-55357900-5d1b-11eb-89b6-8125d45a52f2.png)

```
-----------------------------------------------------------
 Add-on: InfluxDB
 Scalable datastore for metrics, events, and real-time analytics
-----------------------------------------------------------
 Add-on version: 4.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.10  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.1.4
 Home Assistant Supervisor: 2021.01.5
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
```

Supervisor log data from the update

```
21-01-23 00:20:23 INFO (SyncWorker_5) [supervisor.docker.interface] Updating image hassioaddons/influxdb-aarch64:3.7.9 to ghcr.io/hassio-addons/influxdb/aarch64:4.0.0
21-01-23 00:20:23 INFO (SyncWorker_5) [supervisor.docker.interface] Downloading docker image ghcr.io/hassio-addons/influxdb/aarch64 with tag 4.0.0.
21-01-23 00:21:21 INFO (SyncWorker_5) [supervisor.docker.interface] Stopping addon_a0d7b954_influxdb application
21-01-23 00:21:52 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_a0d7b954_influxdb application
21-01-23 00:21:52 WARNING (SyncWorker_3) [supervisor.docker.interface] Can't find hassioaddons/influxdb-aarch64 for cleanup
21-01-23 00:21:52 INFO (MainThread) [supervisor.addons] Add-on 'a0d7b954_influxdb' successfully updated
21-01-23 00:21:54 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/influxdb/aarch64 with version 4.0.0
21-01-23 00:21:55 INFO (MainThread) [supervisor.api.security] /dns/info access from a0d7b954_influxdb
21-01-23 00:26:49 INFO (SyncWorker_0) [supervisor.docker.interface] Stopping addon_a0d7b954_influxdb application
21-01-23 00:26:53 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_a0d7b954_influxdb application
21-01-23 00:26:54 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/influxdb/aarch64 with version 4.0.0
21-01-23 00:26:56 INFO (MainThread) [supervisor.api.security] /dns/info access from a0d7b954_influxdb
21-01-23 00:27:01 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:1337 ssl:default [Connect call failed ('172.30.33.3', 1337)]
21-01-23 00:27:20 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:1337 ssl:default [Connect call failed ('172.30.33.3', 1337)]
```

Only thing left are my dashboards (without data). Everything else is gone! Damn it :-( :-( :-(

**Lesson learned:** never ever update Home Assistant addons quickly, especially when major releases.

@frenck how can I check if data has been deleted?

**Comment by frenck** [comment] 2021-01-23 00:36
InfluxDB itself didn't update or change 🙁

**Comment by bcutter** [comment] 2021-01-23 00:41
So... any idea why and where my data went? :-(

What about https://github.com/hassio-addons/addon-influxdb/pull/107 ?

**Comment by bcutter** [comment] 2021-01-23 00:49
I really have no idea what to do next.
a) Check and provide some logs? How to?
b) Restore my latest snapshot and accept loosing 20 hours of data? Risking to end in the same situation (when updating to v4.0.0 again)?

**Comment by bcutter** [comment] 2021-01-23 01:14
In the addon container there´s a `/data/backup/chronograf.db.1.8.8` from right before the update (timestamp looks good):

`-rw------- 1 root root  64K Jan 23 01:22 chronograf.db.1.8.8` but that looks like a wrong way (too small).

Interestingly `du -sh /data/influxdb` gives 194 MByte which should be the actual size, roughly. So data is there but it´s not used? Missing connection?

I added logs in the op btw.

Sorry to bother you once again @frenck but can you point me in any direction? I know you´re very busy... now time´s running against me too :-(

**Comment by kebel87** [comment] 2021-01-23 01:33
Same issue here, users and database gone.

**Comment by t1gr0u** [comment] 2021-01-23 01:45
Same issue here, users and database gone.

**Comment by bcutter** [comment] 2021-01-23 01:49
When trying to (re)create the "homeassistant" database using the UI it prompts
![grafik](https://user-images.githubusercontent.com/13799156/105564868-5ae38c80-5d24-11eb-8615-8ad01c53a301.png)

Same with user:
![grafik](https://user-images.githubusercontent.com/13799156/105564887-7353a700-5d24-11eb-92ba-4afdc9ffabfb.png)

Configuration.yaml hasn´t changed. Restart of Home Asisstant did not change anything. Restart of InfluxDB addon neither.

That´s out of my comfort zone... totally lost without an expert.

I can spend **some** hours (hours of continued loss of my data not being stored in the long-term database) to help / check / debug things. In case of no expert response I need to restore snapshot to continue data collection, avoid 4.0.0 update and loose trust in HA addon update testing process.

Not sure if a snapshot restoration would work at all... as it only contains the addon data, but not the docker image, right?

```
sha256:980ff6fa3f51cced06e92b068e3f32... | ghcr.io/hassio-addons/influxdb/aarch64:4.0.0 | 513.9 MB |  
-- | -- | -- | --

sha256:bcf44e6b81c0732a3bbe9ba915a97e...                                  Unused | hassioaddons/influxdb-aarch64:3.7.9 | 530.4 MB
-- | -- | --
```

Oh dear I think the snapshot is worth nothing. No way to fix this without experts like @frenck. At least it´s not just me being affected... -.-

**Comment by sinclairpaul** [comment] 2021-01-23 02:06
Snapshots will restore both the previous image and data.

**Comment by bcutter** [comment] 2021-01-23 02:09
Last findings before getting some sleep:

- Chronograf Version has been updated to v1.8.9, has it?
- Connection configuration untouched:
![grafik](https://user-images.githubusercontent.com/13799156/105565616-f6c2c780-5d27-11eb-9e40-426da56e8874.png)

![grafik](https://user-images.githubusercontent.com/13799156/105565623-03472000-5d28-11eb-9df1-08078b0f17cd.png)

We need (one like) fraenck going through 4.0.0 changelog (https://github.com/hassio-addons/addon-influxdb/releases/tag/v4.0.0) and check what change could cause this.

**As we´re talking bout a time-based database importing real-time data (it doesn´t currently...), time´s really precious.**

**Comment by bcutter** [comment] 2021-01-23 02:22
> 
> 
> Snapshots will restore both the previous image and data.

Good news. BUT what are chances it can be fixed? As mentioned data still is there. **Options:**
a) restoring from snapshot. lost data: timeline from snapshot until v4.0.0 update.
b) waiting and hoping. lost data: timeline from v4.0.0 update until <fix>.

Recommendations?

**Comment by sinclairpaul** [comment] 2021-01-23 02:22
> Recommendations?

Restore the snapshot you took before upgrading

**Comment by t1gr0u** [comment] 2021-01-23 02:25
I can confirm what @sinclairpaul has said, you can do a partial restore from your snapshot, meaning you can just select to restore InfluxDB addon then restart the addon. I've just done it myself and it's all back and running with v3.7.9.

You will lose what ever information you had between now and the day of the snapshot.

**Comment by bcutter** [comment] 2021-01-23 02:26
> 
> 
> > Recommendations?
> 
> Restore the snapshot you took before upgrading

Well... "the" snapshot is a auto generated one 23 hours ago (20 before the f*** up update) so I´ll definitely loose 20 hours of data - **as far as I know data is only being transfered "live" from Home Assistant to InfluxDB, there´s no "later bulk load", right?**

As I discovered with this issue updates may fail (and will fail) so in future I won´t trust addon updates but instead will perform a partial snapshot before every single addon update. Should be done automatically for new, naive users like me...

**Comment by sinclairpaul** [comment] 2021-01-23 02:29
> Well... "the" snapshot is an auto generated one 23 hours ago (20 before the f*** up update)

Please consider the fact that the people providing this application for you, do that in their own time, I appreciate this may be an inconvenience to you, however sometimes issues do occur.  It will be looked at, and your patience would be appreciated.

**Comment by t1gr0u** [comment] 2021-01-23 02:30
@bcutter you could perform a snapshot before any updates, just in case, or/and certainly if your data is precious.
Any updates contains a risk, everyone runs their Home Assistant differently and so will have different situations that may or not be taken into account.

**Comment by bcutter** [comment] 2021-01-23 02:47
Restored from snapshot, lost 20 hours of data but it´s better to make this experience now than later. Impact is there but not that horrible yet compared to when smart home is fully built up.

If there´s a need to provide any additional information (I made a manual /data copy from InfluxDB container and created a partial snapshot, both actions with v4.0.0) please let us know. Meanwhile I´ll stay away from the update button 😉 until the root cause is identified and a 4.0.1 fixes it.

Thanks for everyone helping so far ✌

**Comment by Cafun** [comment] 2021-01-23 05:53
I've spent one hour to figuring out what I did wrong when I start a fresh influxdb and get a 401 error on creating a user or database. I'm "glad" I'm not the only one.
I will monitor this topic.

**Comment by MHV33** [comment] 2021-01-23 06:09
I'm also having this problem.  It seems to be authentication related, as others have noted with the 401 error parsing credentials.  When I change the add-on config and set authentication to false, my databases and users show up in InfluxDB.  If I reenable authentication, they disappear again.

So it seems that my databases aren't actually lost, just not visible through the UI when authentication is enabled.

**Comment by SamKr** [comment] 2021-01-23 08:36
Having the same issue, subscribing to this topic

**Comment by MindaugasMeskauskas** [comment] 2021-01-23 09:54
Same issue here after upgrade. I can confirm MHV33 observation that after disabling authentication in config, databases and users reappear.

**Comment by jlaitinen81** [comment] 2021-01-23 10:05
Similar issues here:

Cannot connect to InfluxDB due to 'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=home_assistant (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab67995b50>: Failed to establish a new connection: [Errno -3] Try again'))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.

**Comment by agerrmann** [comment] 2021-01-23 10:06
Same issue here after upgrade. Disable auth works also for me. I leave it this way and wait for an update

**Comment by jlaitinen81** [comment] 2021-01-23 10:12
Restarting Influx AddOn with auth=false allows me to restart it, but it jams my HA recorder. All history information is gone when Influx is running. Have to stop it until a fix...

**Comment by vistalba** [comment] 2021-01-23 10:59
Run into the same issue as well. Had to reconfigue connection and the I got back my DB and Users... but why this happens?

**Comment by marekorok** [comment] 2021-01-23 11:01
> Had to reconfigue connection

You mean you fixed InfluxDB after upate?
Can you share exactly what you did?

**Comment by tjorim** [comment] 2021-01-23 11:36
A potential fix has been verified by me, no need to downgrade. Another upgrade will fix the authentication settings soon.

**Closed** 2021-01-23 11:47 UTC

**Comment by bcutter** [comment] 2021-01-23 12:48
> A potential fix has been verified by me, no need to downgrade. Another upgrade will fix the authentication settings soon.

Great work 👍🏼
So there will be a 4.0.1 or sth. like that popping up, right? Just to make sure for all who downgraded when it is "safe" to update again.

**Comment by frenck** [comment] 2021-01-23 12:49
@bcutter v4.0.1 has been shipped. You might need to reload your add-on store to make the update visible.

**Comment by agerrmann** [comment] 2021-01-23 13:02
All back to normal! Thanks Frenck!

**Comment by bcutter** [comment] 2021-01-23 13:49
> 
> 
> @bcutter v4.0.1 has been shipped. You might need to reload your add-on store to make the update visible.

I reloaded but still only 4.0.0 offered. Are addon updates incremental, so do I need to update to 4.0.0 first before 4.0.1 will be offered? Not brave enough to simply try... :-D

![grafik](https://user-images.githubusercontent.com/13799156/105580024-315d4c00-5d8a-11eb-868d-514dbb438971.png)

**Comment by frenck** [comment] 2021-01-23 13:50
@bcutter Reload the add-on store. Its in the three dotted menu in the top right
